---
- name: Stat directorio antiguo
  stat: path=/home/david/cargaTorneoEcuatorianoA_2015.respaldo
  register: path_antiguo_etl
  tags:
    - etl

- name: Stat directorio actual
  stat: path=/home/david/cargaTorneoEcuatorianoA_2015
  register: path_nuevo_etl
  tags:
    - etl

- name: Copiar archivo comprimido
  remote_user: david
  copy: src=../cargaCuboResultados_0.1.zip dest=/home/david owner=david group=david mode=0644
  tags:
    - etl

- name: Borrar directorio antiguo
  remote_user: david
  sudo: yes
  file: path=/home/david/cargaTorneoEcuatorianoA_2015.respaldo state=absent
  when: path_antiguo_etl.stat.isdir is defined and path_antiguo_etl.stat.isdir == true
  tags:
    - etl

- name: Mover directorio actual a antiguo
  remote_user: david
  command: mv /home/david/cargaTorneoEcuatorianoA_2015 /home/david/cargaTorneoEcuatorianoA_2015.respaldo
  when: path_nuevo_etl.stat.isdir is defined and path_nuevo_etl.stat.isdir == true
  tags:
    - etl

- name: Crear directorio para ETL actual
  remote_user: david
  file: path=/home/david/cargaTorneoEcuatorianoA_2015 state=directory mode=0755
  tags:
    - etl

- name: Descromprimir archivo
  remote_user: david
  unarchive: src=/home/david/cargaCuboResultados_0.1.zip dest=/home/david/cargaTorneoEcuatorianoA_2015 copy=no
  ignore_errors: yes
  tags:
    - etl

- name: Mover comprimido a carpeta actual
  remote_user: david
  command: mv /home/david/cargaCuboResultados_0.1.zip /home/david/cargaTorneoEcuatorianoA_2015/
  tags:
    - etl

- name: Permiso de ejecucion para la etl
  remote_user: david
  file:
    path: /home/david/cargaTorneoEcuatorianoA_2015/cargaCuboResultados/cargaCuboResultados_run.sh
    mode: u=rwx,g=rwx,o=x
  tags:
    - etl

