- hosts: allservers
  vars_files:
  - ../vars/secrets.yml
  - ../vars/marcadores.yml
  - ../vars/bootstrap.yml
  - ../vars/php.yml
  - ../vars/database.yml
  - ../vars/nginx.yml
  roles:
    - { role: geerlingguy.nginx, become: yes, become_method: sudo, tags: ['nginx'] }
    - { role: geerlingguy.php, become: yes, become_method: sudo, tags: ['php'] }
    - { role: geerlingguy.mysql, become: yes, become_method: sudo, tags: ['mysql'] }
